#!/bin/bash
# Usage : give text files of URLs as an input: ./this_file domains.txt 
while read line
do
    if pgrep -u $USER firefox > /dev/null
    then
        firefox --new-tab "$line" &
    else
        firefox "$line" &
        sleep 3                 # You may want to tune this value
    fi < /dev/null
done  
